services:
  meme-collector:
    container_name: meme-collector
    image: ghcr.io/iankulin/meme-collector:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data